### ISSUE TITLE
[BUG] Lack of semicolon makes import silent fail

### ISSUE THREAD

**Issue by Igorgro** [drawdb-io/drawdb#244]
**Describe the bug**
When create table statement does not end with semicolon, then app silently fails

**To Reproduce**
Try to import the following SQL code:
```sql
CREATE TABLE books (
    id INTEGER NOT NULL
) -- notice, there is no semicolon
```

**Expected behavior**
Successful import (because there is only one statement) or explicit error about missing semicolon

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser: Google Chrome 128

**Additional context**
This is the error which is printed in devtools console:
```
Uncaught (in promise) TypeError: r.forEach is not a function
    at Rft (index-CYj_0oVy.js:579:32130)
    at Dft (index-CYj_0oVy.js:579:40234)
    at qr (index-CYj_0oVy.js:579:42056)
    at Object.Os [as onOk] (index-CYj_0oVy.js:579:42799)
    at Object.notifyOk (index-CYj_0oVy.js:54:89416)
    at jFe.handleOk (index-CYj_0oVy.js:54:72435)
    at handleOk (index-CYj_0oVy.js:54:86230)
    at Object.Mwe (index-CYj_0oVy.js:37:9896)
    at jwe (index-CYj_0oVy.js:37:10053)
    at Fwe (index-CYj_0oVy.js:37:10113)
```

**Comment by 1ilit** [comment]
Please reopen if issue still persists
