### ISSUE TITLE
Linux unexpected reserve word

### ISSUE THREAD

**Issue by dwk601** [drawdb-io/drawdb#83]
file:///home/dongwook/Documents/drawdb/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word

I just followed the installation process and when i run npm run dev it shows that message

**Comment by v3n4i** [comment]
have the same issue.. 

ven4i@Matebook13:/mnt/c/Users/ven4i/drawdb$ npm run dev

> client-vite@0.0.0 dev
> vite

file:///mnt/c/Users/ven4i/drawdb/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
ven4i@Matebook13:/mnt/c/Users/ven4i/drawdb$

**Comment by dwk601** [comment]
> What node and npm version are you using

Node.js v12.22.9.

**Comment by JeanFranz73** [comment]
> Node.js v12.22.9.

Vite requires Node.js 18 or above to run properly

Tested on Ubuntu 24.04 LTS
